### PR TITLE
Move resources from v1alpha1 to v1beta1

### PR DESCRIPTION
**Pull request by bison**
Moving from v1alpha1 to v1beta1 version.

### CODE REVIEW

**Comment by ingvagabund** [comment]
```
go test -timeout 60m \
	-v github.com/openshift/cluster-autoscaler-operator/vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e \
	-kubeconfig ${KUBECONFIG:-~/.kube/config} \
	-machine-api-namespace ${NAMESPACE:-openshift-machine-api} \
	-ginkgo.v \
	-ginkgo.noColor=true \
	-args -v 5 -logtostderr true
# github.com/openshift/cluster-autoscaler-operator/vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e
package github.com/openshift/cluster-autoscaler-operator/vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e (test)
	imports github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/autoscaler
	imports github.com/openshift/cluster-autoscaler-operator/pkg/apis/autoscaling/v1alpha1: cannot find package "github.com/openshift/cluster-autoscaler-operator/pkg/apis/autoscaling/v1alpha1" in any of:
	/data/src/github.com/openshift/cluster-autoscaler-operator/vendor/github.com/openshift/cluster-autoscaler-operator/pkg/apis/autoscaling/v1alpha1 (vendor tree)
	/home/origin/.gimme/versions/go1.10.1.linux.amd64/src/github.com/openshift/cluster-autoscaler-operator/pkg/apis/autoscaling/v1alpha1 (from $GOROOT)
	/data/src/github.com/openshift/cluster-autoscaler-operator/pkg/apis/autoscaling/v1alpha1 (from $GOPATH)
FAIL	github.com/openshift/cluster-autoscaler-operator/vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e [setup failed]
```

Please, change the imported path under vendor directory as well + open a PR on actuator-pkg once this PR gets merged.

Thought, this will break our CI for a while since once a new CAO image gets built, we need to update vendored actuator-pkg in all our repos asap.

**Comment by frobware** [comment]
/approve

Let's assume v1beta1 is what was intended for now. if not, lather, rinse, repeat...

**Pull request merged**
