### PR TITLE
Bug 1986090: Do not recreate CA deployment when CA CR is being deleted

### PR DESCRIPTION
**Pull request by JoelSpeed**
This is breaking our tests which use foreground deletion. The CAO fights the GC to delete and recreate the deployment, ensuring that the CA CR never goes away.

I have manually verified that this fixes the broken cluster autoscaler tests we are currently seeing in CI.

### CODE REVIEW

**Review by elmiko — COMMENTED** [review]
this looks like a good solution, just curious if we could add a unit test to check the deletion time stamp part of this?

**Comment by JoelSpeed** [comment]
> just curious if we could add a unit test to check the deletion time stamp part of this?

Reasonable request! I did have a look and our unit tests right now are a bit not great in this area, so it won't be trivial to add a test for this. I will look into adding a unit test for this tomorrow though.

**Comment by elmiko** [comment]
> Reasonable request! I did have a look and our unit tests right now are a bit not great in this area, so it won't be trivial to add a test for this. I will look into adding a unit test for this tomorrow though.

sounds good, i was hoping we could slip this into the reconcile test but maybe that was optimistic of me ;)

**Review by alexander-demichev — APPROVED** [review]
/approve

**Comment by JoelSpeed** [comment]
/override ci/prow/e2e-aws-operator

The tests are broken, I've manually verified this, once this merged we can get the rest of the tests fixed

**Pull request merged**
