### PR TITLE
[OCPCLOUD-813] Bump scripts to Go 1.13

### PR DESCRIPTION
**Pull request by JoelSpeed**
Bumps scripts and docker images to Go 1.13

### CODE REVIEW

**Comment by enxebre** [comment]
/approve
should be otherwise covered by https://github.com/openshift/cluster-autoscaler-operator/pull/146/commits/0bc4a9c14e4a3ed249bddc64f414c7e0de585af5

**Comment by JoelSpeed** [comment]
Superseded by #146

**Comment by enxebre** [comment]
We can close this now as it was covered by https://github.com/openshift/cluster-autoscaler-operator/pull/146

**Pull request closed without merging**
