### PR TITLE
OCPBUGS-18954: Ensure status reporter caches exit if they don't sync

### PR DESCRIPTION
**Pull request by JoelSpeed**
We are seeing sometimes, that the Cluster Autoscaler status never gets reported. Looking at the logic, it's possible here that we wait forever for the informers to sync, but, if they never actually sync, the status won't get reported.
I'm not sure why they wouldn't sync, but, having a timeout seems reasonable to prevent this infinite hang.

If we start seeing this timeout hit repeatedly, then my theory is correct, and we can then investigate why the informers aren't syncing correctly.

### CODE REVIEW

**Review by elmiko — COMMENTED** [review]
makes sense to me, i have a question about one of your comments though.

> If we start seeing this timeout hit repeatedly,

how will we know?  i'm just curious what the signal from ci will look like.

/lgtm
/approve

**Comment by JoelSpeed** [comment]
> how will we know? i'm just curious what the signal from ci will look like.

CI has a check already that will report if a pod has restarted many times, so, if it becomes an issue and the pod is restarting every 30 seconds, the existing suite should tell us

**Pull request merged**
