### PR TITLE
Add expect for cluster operator status

### PR DESCRIPTION
**Pull request by enxebre**
- Introduce expect for cluster operator status 
- Fix dependency cluster operator status name, machine-api
- Better logging

### CODE REVIEW

**Comment by enxebre** [comment]
cc @bison

**Comment by ingvagabund** [comment]
Looks good. It's basically copy-paste of what we have in mao [1], right? Let's re-consider moving this test into common repo and vendoring it back here. Not a blocker for the PR.

[1] https://github.com/openshift/machine-api-operator/blob/master/test/e2e/operator_expectations.go#L73

/approve

**Comment by ingvagabund** [comment]
`no kind is registered for the type v1.ClusterOperator`

**Pull request merged**
